### ISSUE TITLE
Add support for SSL/TLS termination

### ISSUE THREAD

**Issue by hyperioxx** [hyperioxx/frontman#13]
Currently, Frontman does not support SSL/TLS termination. This means that clients cannot communicate with Frontman over HTTPS, which is becoming increasingly important for security reasons.

Adding support for SSL/TLS termination would allow Frontman to terminate SSL/TLS connections from clients and forward requests to backend services over HTTP. This would enable clients to communicate with Frontman over HTTPS, providing an additional layer of security.

Some possible tasks for implementing SSL/TLS termination in Frontman could include:

- Updating the BackendService struct to include an optional field for an SSL/TLS certificate and key
- Adding a new command-line flag or configuration option to enable SSL/TLS termination
- Updating the FrontmanServer struct to support HTTPS connections and SSL/TLS termination
- Adding support for automatically obtaining and renewing SSL/TLS certificates from Let's Encrypt or another certificate authority
- SSL/TLS termination is a critical feature for many production deployments of Frontman, and we should prioritize adding this feature as soon as possible.

**Comment by ofonimefrancis** [comment]
How do you want to get the cert.perm and key.perm? A location in the application or via a flag?

**Comment by hyperioxx** [comment]
@ofonimefrancis  Thanks for bringing that up! We could provide users with the ability to specify the location of the certificate and private key through a flag, or by configuring the paths to the files in the application configuration file. Alternatively, we could also support obtaining the certificate and private key from a certificate authority or key management service. What do you think would be the most convenient option for users?

**Comment by ofonimefrancis** [comment]
I think a location to where the certs are located would work best for the
MVP and maybe build on that later.

**Comment by hyperioxx** [comment]
@ofonimefrancis 100% Agree

**Comment by hyperioxx** [comment]
@ofonimefrancis was working last night and added a config file and i thought about the TLS/SSL configuration 

Thoughts?

```
global:
  service_type: SERVICE_TYPE
  services_file: SERVICES_FILE
  redis_namespace: REDIS_NAMESPACE
  redis_uri: REDIS_URI

api:
  addr: API_ADDR
  ssl_enabled: true
  ssl:
    - cert: /path/to/cert1.pem
      key: /path/to/key1.pem

gateway:
  addr: GATEWAY_ADDR
  ssl_enabled: true
  ssl:
    - cert: /path/to/cert1.pem
      key: /path/to/key1.pem

logging:
  level: LOG_LEVEL
```
